#ifndef TOKENCODES_H
#define TOKENCODES_H

using namespace std;

enum TokenCodes
{
    PLUS, MINUS, TIMES, SLASH, MOD, LPAREN, RPAREN, LBRACE,
    RBRACE, COMMA, SEMICOLON, OR, AND, ASSIGN, EQL, NOT, NEQ,
    LSS, LEQ, GTR, GEQ, BOOLSYM, DOSYM, ELSESYM, FALSESYM,
    FLOATSYM, FORSYM, IFSYM, INTSYM, PRINTFSYM, RETURNSYM,
    SCANFSYM, TRUESYM, VOIDSYM, WHILESYM, IDENT, NUMLIT, EOI,
    NAL
};

#endif